fix(ci): suppress warning causing failure to CI job
/__w/libs/libs/build/_deps/glog-src/src/symbolize.cc:705:10: error: writing 8 bytes into a region of size 0 [-Werror=stringop-overflow=]
  705 |     *ptr = *start;
      |     ~~~~~^~~~~~~~

Signed-off-by: irozzo-1A <iacopo@sysdig.com>