fix(build): add an explicit constructor call
While the shared pointer could be constructed implicitly from
std::move(unique_ptr), this causes a gcc warning:

	userspace/libsinsp/plugin_table_api.cpp: In instantiation of ‘std::shared_ptr<libsinsp::state::table_entry> plugin_table_wrapper<KeyType>::add_entry(const KeyType&, std::unique_ptr<libsinsp::state::table_entry>) [with KeyType = bool]’:
	userspace/libsinsp/plugin_table_api.cpp:578:48:   required from here
	userspace/libsinsp/plugin_table_api.cpp:602:35: error: redundant move in return statement [-Werror=redundant-move]
	  602 |                 return std::move(e);
	      |                                   ^
	userspace/libsinsp/plugin_table_api.cpp:602:35: note: remove ‘std::move’ call

The move is very much *not* redundant but gcc can't see this

Signed-off-by: Grzegorz Nosek <grzegorz.nosek@sysdig.com>