fix(driver): add preprocessor guards for oldest 2.6.32 kernels
recent updates to the driver broke the driver build for very
ancient 2.6.32 kernels on CentOS 6 (e.g. 2.6.32-71.24.1.el6):

socketcall_to_syscall.h:208:7: error: 'SYS_SENDMMSG' undeclared (first use in this function)
   case SYS_SENDMMSG:
        ^
So add the appropriate preprocessor guards to get it to compile.

Signed-off-by: Gerlando Falauto <gerlando.falauto@sysdig.com>